### PR TITLE
Feature/layout and controls update

### PR DESCRIPTION
**Pull request by JaroslavSoldat**
- Switch mitigation controls to toggle buttons group
- Switch mitigation controls to slide buttons
- Move graph to first position of layout
- Fix graph responsivity

### CODE REVIEW

**Comment by Petr26** [comment]
image
I would lower font size, its very big IMO.

**Comment by Petr26** [comment]
image
Po chvilce v appce se mi zmeni rozliseni, asi na mobilni, nebo nevim..

**Comment by JaroslavSoldat** [comment]
Graph is NOT fully responsive. :(
With my ugly patch graph is able to correctly set its size at the beginning. 
But as it resizes, the graph gradually grows and takes up more and more space. :/

**Comment by JaroslavSoldat** [comment]
Feel free to tweak root font size (and whole layout) via settings in `frontend/src/styles.scss` 👍🏻

**Review by Petr26 — APPROVED** [review]

**Pull request merged**
